name: Build and push Docker image
  uses: docker/build-push-action@v4
  with:
     context: .
     file: ./Dockerfile
     push: true
     tags: myimage:latest
     outputs: type=docker,dest=/tmp/myimage.tar
