name: docker build

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  balena_cloud_build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@v0.23.0
        id: build
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
